[package]
name = "crab-launcher"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["core", "api"]

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
crab-launcher-core = { path = "core" }
